"""create product and product group table

Revision ID: 34c5e4d31996
Revises: 
Create Date: 2026-02-17 17:40:05.275362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34c5e4d31996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('system_product_id', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('qb_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('base_image_url', sa.String(length=1000), nullable=True),
    sa.Column('product_url', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('dbs_status', mysql.TINYINT(), nullable=True),
    sa.Column('iqr_status', mysql.TINYINT(), nullable=True),
    sa.Column('iqr_height_status', mysql.TINYINT(), nullable=True),
    sa.Column('iqr_width_status', mysql.TINYINT(), nullable=True),
    sa.Column('iqr_depth_status', mysql.TINYINT(), nullable=True),
    sa.Column('final_status', mysql.TINYINT(), nullable=True),
    sa.Column('skip_status', mysql.TINYINT(), nullable=True),
    sa.Column('skip_status_updated_date', sa.DateTime(), nullable=True),
    sa.Column('analyzed_date', sa.DateTime(), nullable=True),
    sa.Column('dimension_status', sa.String(length=50), nullable=True),
    sa.Column('dimension_failed', sa.String(length=50), nullable=True),
    sa.Column('iteraration_total', sa.Integer(), nullable=True),
    sa.Column('iteraration_closed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['product_group.group_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('product_group')
    # ### end Alembic commands ###
