"""item_matching tables

Revision ID: 755823327965
Revises: 64a861eb7441
Create Date: 2026-02-25 13:57:32.357440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755823327965'
down_revision: Union[str, Sequence[str], None] = '64a861eb7441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_competitor_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=150), nullable=False),
    sa.Column('part_number', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_status', sa.String(length=20), nullable=True),
    sa.Column('sku_score', sa.Float(), nullable=True),
    sa.Column('url_score', sa.Float(), nullable=True),
    sa.Column('price_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching_system_product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=150), nullable=False),
    sa.Column('part_number', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('matched_ref_id', sa.Integer(), nullable=True),
    sa.Column('matched_date', sa.DateTime(), nullable=True),
    sa.Column('review_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matched_ref_id'], ['matching_competitor_product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_system_product')
    op.drop_table('matching_competitor_product')
    # ### end Alembic commands ###
