"""add_outlier_mode_column_in_product_table

Revision ID: a08cf1daa1a2
Revises: 301c5db61dcf
Create Date: 2026-02-20 14:22:26.413260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import TINYINT


# revision identifiers, used by Alembic.
revision: str = 'a08cf1daa1a2'
down_revision: Union[str, Sequence[str], None] = '301c5db61dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('outlier_mode', TINYINT(), nullable=True, comment='0=Autometic, 1=Manually'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'outlier_mode')
    # ### end Alembic commands ###
